### Send POST request with json body
POST http://localhost:5000/feed
Content-Type: application/json

{
  "title": "건국대학교 데이트에요",
  "content": "건국대학교 호수 한바퀴 돌았습니다~~~",
  "uploadtime": "2023-10-11T20:52:14",
  "image": [
    "첫 번째 사진 URL",
    "두 번째 사진 URL"
  ],
  "location": [
    {
      "datetime": "2023-10-11T20:52:14",
      "lat": 127.333,
      "lng": 36.123
    },
    {
      "datetime": "2023-10-11T20:53:14",
      "lat": 127.353,
      "lng": 36.145
    },
    {
      "datetime": "2023-10-11T20:54:13",
      "lat": 127.453,
      "lng": 36.245
    },
    {
      "datetime": "2023-10-11T20:55:14",
      "lat": 127.5653,
      "lng": 36.15315
    }
  ],
  "visit": [
    {
      "datetime": "2023-10-11T20:43:14",
      "endtime": "2023-10-11T21:55:14",
      "lat": 127.333,
      "lng": 36.123,
      "lat_set": 127.555,
      "lng_set": 36.555,
      "staytime": 60,
      "name": "공학관"
    },
    {
      "datetime": "2023-10-11T20:57:14",
      "endtime": "2023-10-11T21:59:14",
      "lat": 127.333,
      "lng": 36.123,
      "lat_set": 127.565,
      "lng_set": 36.565,
      "staytime": 60,
      "name": "신공학관"
    }
  ]
}
