jwt-secret-key: "sM5qi24RmAeNP0m"

server:
  port: 5000

spring:
  mail:
    protocol: smtp
    host: smtp.gmail.com
    port: 587
    username: vectokonkuk@gmail.com
    password: "xfpc boqs lziy tejt"
    properties:
      smtp.auth: true
      mail:
        smtp:
          starttls:
            enable: true
            required: true
    test-connection: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.default_batch_fetch_size: 1000

  datasource:
    url: jdbc:mysql://vecto-db.cxy0uswe2vyr.ap-northeast-2.rds.amazonaws.com:3306/vecto
    username: admin
    password: 1a2a3a4a5a

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379

jwt:
  bearer: Bearer
  secret: sM5qi24RmAeNP0m
  access-expiration: 3600000 # 1시간 (단위: ms)
  access-header: AUTHORIZATION # Access Token 헤더
  refresh-expiration: 86400000 # 1일 (단위: ms)
  refresh-header: AUTHORIZATION-REFRESH # Refresh Token 헤더

cloud:
  aws:
    s3:
      accessKey: AKIAW3MD6JE3OQZICBFX
      secretKey: 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
      region: ap-northeast-2

fcm:
  key:
    path: firebase/vecto-fc688-firebase-adminsdk-yyxm5-1527aad64c.json
    scope: https://www.googleapis.com/auth/cloud-platform














